#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --time=1:00:00
#SBATCH --account=m18

module swap PrgEnv-cray PrgEnv-gnu
module load cray-hdf5-parallel
module load python/2.7.10
module load swig
module load numpy
module load scipy
module load cython
module load mpi4py
#module load cmake
module load pkgconfig

export MPI_DIR=$CRAY_MPICH2_DIR

export PETSC_DIR=/home/rfarrington/petsc-3.6.1
export PETSC_ARCH=arch-linux2-c-opt
export PYTHONPATH=$PYTHONPATH:/group/m18/Apps/Underworld2-master

cd ../models

aprun -n 16 python T0.py
