#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --time=1:00:00
#SBATCH --account=m18

module swap PrgEnv-cray PrgEnv-gnu
module load cray-hdf5-parallel
module load python/2.7.10
module load swig
module load numpy
module load scipy
module load cython
module load mpi4py
#module load cmake
module load pkgconfig

# python things
export PYTHONPATH=$PYTHONPATH:/ivec/cle52/magnus/python/2.7.6/six/1.9.0/lib/python2.7/site-packages/

# Petsc installed in shared space /group/m18/Apps
export MPI_DIR=$CRAY_MPICH2_DIR
export PETSC_DIR=/group/m18/Apps/petsc-3.6.3
export PETSC_ARCH=arch-linux2-c-opt

export PYTHONPATH=$PYTHONPATH:/group/m18/dsandiford/underworld2

cd ..

aprun -n 16 python eba_slab.py D 1 dp.np=21.0 md.ppc=75 md.RES=128 dp.opmaxAge*=0.2 dp.MANTLETOCRUST*=1.5 dp.eta_max_crust*=3. dp.ysMax*=0.08 dp.Adf*=1.25 dp.Vdf*=0.9 dp.Vds*=0.9 dp.Alm*=0.003 dp.Wlm*=1.1 dp.Elm*=0.5
