#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --time=1:00:00
#SBATCH --account=m18

module swap PrgEnv-cray PrgEnv-gnu
module load cray-hdf5-parallel
module load python/2.7.10
module load swig
module load numpy
module load scipy
module load cython
module load mpi4py
#module load cmake
module load pkgconfig

export MPI_DIR=$CRAY_MPICH2_DIR

export PETSC_DIR=/home/rfarrington/petsc-3.6.1
export PETSC_ARCH=arch-linux2-c-opt
export PYTHONPATH=$PYTHONPATH:/group/m18/Apps/Underworld2-master

cd ..

aprun -n 16 python eba_slab.py D 1 dp.np=21.0 md.ppc=75 md.RES=128 dp.opmaxAge*=0.2 dp.MANTLETOCRUST*=1.5 dp.eta_max_crust*=3. dp.ysMax*=0.08 dp.Adf*=1.25 dp.Vdf*=0.9 dp.Vds*=0.9 dp.Alm*=0.003 dp.Wlm*=1.1 dp.Elm*=0.5
