#!/bin/bash
#PBS -P m18
#PBS -q normal
#PBS -l walltime=03:00:00
#PBS -l mem=32GB
#PBS -l ncpus=16
#PBS -l wd

cd ..

# setup the environment for building and running Underworld on raijin.nci.org
module purge
module load dot pbs gcc/5.2.0 hdf5/1.8.14p python/2.7.11 python/2.7.11-matplotlib openmpi/1.8.4

# Petsc and python modules installed in shared space /project/m18/opt
#  'Local' pip used to install mpi4py
#  Swig, h5py and petsc-3.6.3 are all installed manually using the cluster environment as per the 'module load' above
#    Trick to installing swig. I had to create a directory called ?^?^?tmp/?^?^? in my home directory for its configure system to work.

export HDF5_VERSION=1.8.14
export PETSC_DIR=/projects/m18/opt/petsc-3.6.3
export PYTHONPATH=/projects/m18/opt:$PYTHONPATH
export PATH=/projects/m18/opt/swig-3.0.10/bin:$PATH
module list

export MPIRUN=mpiexec
export PYTHONPATH=/short/m18/dds563/underworld2/:$PYTHONPATH

$MPIRUN -np $PBS_NCPUS --mca mpi_warn_on_fork 0 python eba_slab.py A 1 md.ppc=50 md.RES=192 dp.eta_max_crust*=1.33 dp.opmaxAge*=0.2 dp.Alm*=3.0 dp.eta0*=1.
